### ISSUE TITLE
Stablilty

### ISSUE THREAD

**Issue by appreciated** [Wnt/vaadin-fiddle#2]
[I am using Vaadin Fiddle to show the users of my Addon example code.](https://vaadin.com/directory#!addon/material) 
A few minutes after I update to the Examples with a valid Url Vaadin Fiddle seems to be down (I cannot even access /editor/, I'am just getting a hello from nginx). It seems that there might be some issues when "many" (maybe 10 - max. 50?) concurrent users look at the same fiddle in parallel.

**Comment by Wnt** [comment]
Hi,
thank you for your interest in this project. Unfortunately the platform and especially the instance deployed to vaadinfiddle.com is not quite ready for prime time yet. While the waiting for this project to mature, you could try hosting your add-on demos on herokuapp.com. I've heard you can run simple Vaadin add-on demos there even for free.

P.S. Sorry for the late reply, for some reason I was not subscribed about new issues in the project.

Best regards,
Jonni

**Comment by appreciated** [comment]
Hi Jonni, 
A pitty that vaadinfiddle does not yet meet my requirements but yeah as you say it needs some more time to mature, for a demo in Vaadin Directory it is unfortunately still a bit too unstable. 
It is still a great project though. 
Anyways thank you very much for you tipp with herokuapp.com, setting it up with spring boot was really easy and it is also for free amazing! I will close this issue since I guess you probably are aware of it by yourself 😉.
